app/views/calculator.scala.html, app/views/results.scala.html
Updated formatting of table results in line with GDS standard.
=> PAAC-118: Added minimum step value to calculator input fields.

app/form/CalculatorForm.scala, conf/messages, test/form/CalculatorFormSpec.scala, test/routes/paacRoutes.scala
Also added paacRoutes test file
=> PAAC-161: Added more CalculatorForm tests

app/controllers/CalculatorController.scala, app/form/CalculatorForm.scala, app/views/calculator.scala.html, conf/application.conf, conf/messages
=> PAAC-118: Added minimum value with error display for calculator page.

app/form/CalculatorForm.scala, app/models/Contribution.scala, app/views/calculator.scala.html, conf/messages, test/form/CalculatorFormSpec.scala, test/models/ContributionSpec.scala, test/models/PensionResultSpec.scala
Added validation for empty amounts.
Highlight field label in red if there is an error.
=> PAAC-118: Fixed error message to show correct tax year.

app/connector/CalculatorConnector.scala, app/controllers/CalculatorController.scala, app/models/PensionResult.scala, app/views/calculator.scala.html, conf/application.conf, project/MicroService.scala, test/connector/CalculatorConnectorSpec.scala, test/controllers/CalculatorControllerSpec.scala, test/controllers/DevAssetsSpec.scala
Improved code coverage of tests to > 90%.
=> PAAC-118: Made calculate endpoint configurable.

app/controllers/PensionInputsController.scala, app/controllers/ReviewTotalAmountsController.scala, app/form/PensionInputForm.scala, app/views/pensionInputs.scala.html, app/views/review_amounts.scala.html, conf/paac.routes
Updated pension input to save to keystore pence value to avoid issues with marshall to and from bigdecimal values and associated floating point errors.
=> PAAC-173: Implemented edit pension input amount.

app/controllers/ReviewTotalAmountsController.scala, app/form/PensionInputForm.scala, app/models/Contribution.scala, app/models/PensionResult.scala, app/views/results.scala.html, app/views/review_amounts.scala.html, test/models/ContributionSpec.scala, test/models/PensionResultSpec.scala
Updated review and results pages to use new models correctly.
=> PAAC-162: Updated models to reflect changes in backend.

app/models/Contribution.scala, app/views/results.scala.html, test/models/ContributionSpec.scala
=> PAAC-207: Fixed results page None.get exception.

app/controllers/PensionInputs1516Period1Controller.scala, app/controllers/PensionInputs1516Period2Controller.scala, app/controllers/PensionInputsController.scala, app/controllers/ReviewTotalAmountsController.scala, app/form/CalculatorForm.scala, app/models/Contribution.scala, app/models/PensionResult.scala, app/views/review_amounts.scala.html, test/controllers/ReviewTotalAmountsControllerSpec.scala, test/models/ContributionSpec.scala, test/models/PensionResultSpec.scala
Updated review page to display contributions if present.
Update review controller and calculator form to use contributions.
=> PAAC-291: Updated models with changes from backend service.

app/controllers/PensionInputs1516Period1Controller.scala, app/controllers/PensionInputs1516Period2Controller.scala, app/controllers/PensionInputsController.scala, app/controllers/ReviewTotalAmountsController.scala, app/form/CalculatorForm.scala, app/views/pensionInputs.scala.html, app/views/pensionInputs_1516_period1.scala.html, app/views/pensionInputs_1516_period2.scala.html, app/views/review_amounts.scala.html, conf/messages, test/controllers/PensionInputs1516Period1ControllerSpec.scala, test/controllers/PensionInputs1516Period2ControllerSpec.scala, test/controllers/PensionInputsControllerSpec.scala, test/controllers/ReviewTotalAmountsControllerSpec.scala, test/form/CalculatorFormSpec.scala
Updated all html views, controllers and tests affected.
=> PAAC-291: Updated CalculatorForm to hold both defined benefits and contributions.

app/controllers/BaseFrontendController.scala, app/controllers/PensionInputs1516Period1Controller.scala, app/controllers/PensionInputs1516Period2Controller.scala, app/views/pensionInputs_1516_period1.scala.html, app/views/pensionInputs_1516_period2.scala.html, app/views/taxyearselection.scala.html, conf/messages, conf/paac.routes, test/controllers/PensionInputs1516Period1ControllerSpec.scala, test/controllers/PensionInputs1516Period2ControllerSpec.scala, test/controllers/RedirectControllerSpec.scala, test/controllers/TaxYearSelectionSpec.scala
Validation added for no years selected in tax year selection page.
=> PAAC-159: Clicking back button returns to review page if editing a value

app/models/PensionResult.scala, app/views/pensionInputs_201516.scala.html, app/views/results.scala.html, test/models/PensionResultSpec.scala
Updated models for results page.
=> PAAC-483: New results page following prototype version 5.

app/views/results.scala.html, app/views/review_amounts.scala.html, conf/messages
Updated results and review pages to match version 5 of prototype.
=> PAAC-483: Added missing messages.

app/controllers/PensionInputs201617Controller.scala, app/views/pensionInputs_201617.scala.html, conf/application.conf, conf/messages, conf/paac.routes, test/controllers/PensionInputs201617ControllerSpec.scala, test/controllers/TaxYearSelectionSpec.scala, test/form/CalculatorFormSpec.scala
Also with merged branch PAAC-498.
=> PAAC-254: PIA for tax year 2016/2017 for Defined Benefit and Defined Contribution

app/config/ApplicationGlobal.scala, app/controllers/BaseFrontendController.scala, app/controllers/YesNoThresholdIncomeController.scala, app/service/KeystoreService.scala, app/views/adjusted_income_1617_input.scala.html, app/views/postTriggerPensionInputs.scala.html, app/views/yesno_for_threshold_income.scala.html, conf/application.conf, conf/messages, test/controllers/YesNoThresholdIncomeControllerSpec.scala
- Updated threshold yes/no and input pages read values from configuration.
- Updated threshold yes/no and input to save values unique to the user journey year.
=>  PAAC-86: Made trigger amount field id unique within the page.

app/controllers/AdjustedIncome1617InputController.scala, app/controllers/DateOfMPAATriggerEventController.scala, app/views/adjusted_income_1617_input.scala.html, app/views/contributionReviewTable/table.scala.html, app/views/review_amounts.scala.html
- Updated check your answers to use new template.
- Updated adjusted input and date of trigger controllers to be slightly more efficient.
=> PAAC-536: Moved check your answers table into it's own template to enable reuse.

app/views/results.scala.html, test/controllers/AdjustedIncome1617InputControllerSpec.scala
Also fixed PAAC-495 defect. Updated AdjustedIncome1617InputControllerSpec unit tests.
=> PAAC-548: Updated results page to display MPAA column only when MP Savings are Applicable. 

app/controllers/PensionInputsController.scala, app/controllers/action/CheckSessionAction.scala, app/controllers/action/ReadKeystoreAction.scala, app/controllers/action/WriteKeystoreAction.scala, app/form/CalculatorForm.scala, app/form/DateOfMPAATriggerEventForm.scala, app/models/CalculatorFormFields.scala, app/service/KeystoreService.scala, app/service/UserJourneyService.scala, test/BaseSpec.scala, test/controllers/DateOfMPAATriggerEventControllerSpec.scala, test/controllers/PostTriggerPensionInputsControllerSpec.scala, test/controllers/ReviewTotalAmountsControllerSpec.scala, test/controllers/SelectSchemeControllerSpec.scala, test/controllers/YesNoMPAATriggerEventAmountControllerSpec.scala, test/controllers/YesNoThresholdIncomeControllerSpec.scala, test/controllers/action/CheckSessionActionSpec.scala, test/controllers/action/DataRequestSpec.scala, test/controllers/action/ReadKeystoreActionSpec.scala, test/controllers/action/WriteKeystoreActionSpec.scala, test/form/CalculatorFormSpec.scala, test/models/CalculatorFormFieldSpec.scala, test/models/ContributionSpec.scala, test/service/KeystoreServiceSpec.scala, test/service/UserJourneyServiceSpec.scala
Increased code coverage.
Minor refactoring.
=> PAAC-530: Added logging to keystore service.

app/views/date_of_mpaa_trigger_event.scala.html, app/views/review_amounts.scala.html
Fixed issue with display of period 1 in Check Your Answers page when trigger not occurred.
=> PAAC-598: Removed pence from hidden trigger amount fields.

app/models/Contribution.scala, app/views/contributionReviewTable/table.scala.html, app/views/results.scala.html
Fix also applied to review table header border.
=> PAAC-621: Updated results page to display unused with carry forwards.

app/controllers/AdjustedIncome1617InputController.scala, app/controllers/DateOfMPAATriggerEventController.scala, app/controllers/PensionInputs201516Controller.scala, app/controllers/PensionInputs201617Controller.scala, app/controllers/PensionInputsController.scala, app/controllers/PostTriggerPensionInputsController.scala, app/controllers/YesNoMPAATriggerEventAmountController.scala, app/controllers/YesNoThresholdIncomeController.scala, app/form/package.scala, app/service/UserJourneyService.scala, app/views/adjusted_income_1617_input.scala.html, app/views/pensionInputs.scala.html, app/views/pensionInputs_201617.scala.html, app/views/yesno_for_threshold_income.scala.html, conf/paac.routes, test/controllers/AdjustedIncome1617InputControllerSpec.scala, test/controllers/PensionInputs201516ControllerSpec.scala, test/controllers/PensionInputs201617ControllerSpec.scala, test/controllers/PensionInputsControllerSpec.scala, test/controllers/PostTriggerPensionInputsControllerSpec.scala, test/controllers/ReviewTotalAmountsControllerSpec.scala, test/controllers/YesNoMPAATriggerEventAmountControllerSpec.scala, test/controllers/YesNoThresholdIncomeControllerSpec.scala, test/service/UserJourneyServiceSpec.scala
Updated urls to include year where appropriate in preparation for Google Analytics.
=> PAAC-606: Fields now check for empty string.

app/views/results.scala.html, conf/application.conf, conf/messages
Updated to show 4 years instead of 3.
=> PAAC-647: Updated results to show AA with CCF.

app/config/ApplicationConfig.scala, app/views/common/main.scala.html, app/views/common/paacMain.scala.html, app/views/contributionReviewTable/table.scala.html, app/views/pensionInputs_201516.scala.html, app/views/pensionInputs_201617.scala.html, app/views/results.scala.html, conf/application.conf
Updated main and paacMain templates to propogate through the additional google analytic calls.
Updated application.conf with temporary google analytics id.
=> PAAC-671: Implemented Google Analytics events on pages.

app/views/common/main.scala.html, app/views/error_template.scala.html, app/views/helpers/gaEvent.scala.html, app/views/pensionInputs.scala.html, app/views/pensionInputs_201516.scala.html, app/views/pensionInputs_201617.scala.html, app/views/results.scala.html, app/views/review_amounts.scala.html
Moved reporting of inputs to Google Analytics to review page.
Added Google Analytics to Error page for monitoring.
=> PAAC-671: Ensure all calls to Google Analytics have anonymised IPs.

app/controllers/StartPageController.scala, app/controllers/TaxYearSelectionController.scala, app/views/startPage.scala.html, app/views/taxyearselection.scala.html, conf/messages, conf/messages.cy, conf/paac.routes
Updated tax year selection to have back link.
=> PAAC-712: Re-created start page with new content and welsh language switch.

app/views/common/main.scala.html, app/views/pensionInputs.scala.html, app/views/startPage.scala.html, conf/messages, conf/messages.cy
=> PAAC-732: Removed 'Inc Carry Forwards' from result table headers.
